apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ortopedica-api-dev-fernandoe-com
spec:
  secretName: ortopedica-api-dev-fernandoe-com-tls
  issuerRef:
    name: ortopedica-letsencrypt
  commonName: ortopedica-api.dev.fernandoe.com
  dnsNames:
    - ortopedica-api.dev.fernandoe.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ortopedica-api.dev.fernandoe.com
