language: generic
sudo: required
services:
- docker

install:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $TRAVIS_REPO_SLUG:$TAG .

script:
  - make ci.test
